### ISSUE TITLE
Een betere manier dan database wachtwoorden in de code

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-webshop-database-florian#10]
Je geeft hier zelf aan dat dit niet goed voelt,
https://github.com/JeroenHeemskerk/educom-webshop-database-florian/blob/a705fea2efe91015c76708a54b0945868fe8de60/communication.php#L3-L8
Daar heb je gelijk in, je wilt eigenlijk geen wachtwoorden inchecken in GIT. Een veelgebruikte optie is om lokaal een .env file te hebben die je niet incheckt, of zoals hieronder is aangegeven om Environment variabelen te gebruiken.

Je kunt 4 [environment variabeles definiëren in Windows](https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/) genaamd
* MYSQL_FLORIAN_WEBSHOP_HOST = localhost
* MYSQL_FLORIAN_WEBSHOP_DATABASE = florians_webshop
* MYSQL_FLORIAN_WEBSHOP_USER = florians_webshop_user
* MYSQL_FLORIAN_WEBSHOP_PASSWORD = _9Cq>&djZFE>g5i

In PHP kan je dan doen 
```php
 $servername = getenv("MYSQL_FLORIAN_WEBSHOP_HOST"); 
 $dbname = getenv("MYSQL_FLORIAN_WEBSHOP_DATABASE"); 
 $username = getenv("MYSQL_FLORIAN_WEBSHOP_USER"); 
 $password = getenv("MYSQL_FLORIAN_WEBSHOP_PASSWORD");
```

**Comment by uknowwho** [comment]
Ik heb het opgelost met de genoemde Windows Variabelen. Voeg die dus lokaal toe voor replicatie op eigen machine.
